language: ruby
rvm:
- 2.6.5

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - JEKYLL_ENV=production

sudo: false # route your build to the container-based infrastructure for a faster build