title: Everything Clare Knows
description: >- # this means to ignore newlines until "baseurl:"
  A wiki site hosting ALL OF CLARE'S NOTES. Be afraid. Be very afraid.  
  Or if you like you can just be excited! Clare is.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clare-wiki.herokuapp.com/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: claresudbery
github_username:  claresudbery

# Build settings
markdown: redcarpet
theme: minima

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "highlight", "with_toc_data"]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor

# Allow links to other sections in the same doc
# Referenced here: https://stackoverflow.com/questions/4629675/jekyll-markdown-internal-links
kramdown:
  auto_ids: true

# Plugins
plugins:
  - jekyll-sitemap

# Category archive plugin (see https://github.com/shigeya/jekyll-category-archive-plugin)
#category_archive:
#  - layout: category_archive
