require 'rubygems'
require 'sinatra'
require 'omniauth-auth0'
require 'dotenv/load'

#### Sinatra App ####
class App < Sinatra::Base
  enable :sessions
  set :session_secret, ENV['SESSION_SECRET']

  # Ensure we use TLS in all non-local environments
  before do
    if !request.path.start_with?('/assets/')
      if request.host != 'localhost'
        if !request.secure?
          halt 400, File.read("_site/400.html")
        end
      end
    end
  end

  #### Display wiki pages generated by Jekyll ####
  get '/*' do
    fname = params[:splat][0]

    if !fname.start_with?('assets/')
      # If not authenticated and auth not disallowed, send to login page
      if !session[:authenticated] && !(ENV['AUTH_DISABLED'].to_s.downcase == 'true')
        session['redirect_to'] = "/#{fname}"
        return redirect to('/auth/auth0')
      end
    end
    
    fname = 'index' if fname.empty?
    path = File.join("_site", fname.to_s)
    if File.exist?(path)
      return send_file(path)
    else
      if File.exist?("#{path}.html")
        return send_file("#{path}.html")
      end
    end

    status 404
    File.read("_site/404.html")
  end
end
