#!/bin/bash

md_path=$1
wiki_file=$2
docx_path=$3
docx_file_and_path="$docx_path$wiki_file.docx"

echo "docx_file_and_path: $docx_file_and_path"
echo "converted markdown (might be temp): $md_path"

# Do the conversion from Word to Git-flavoured Markdown
# NB: The lua script removes the annoying blank lines that get inserted between every bullet point.
pandoc -t gfm --extract-media . --lua-filter ~/scripts/tightenLists.lua -o "$md_path" "$docx_file_and_path" 

